name: Build and Deploy Spring Boot with Docker

on:
  push:
    branches:
      - spring

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/venkat5596/spring:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: venkat5596
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
